Global:
  use_gpu: true
  epoch_num: 5
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/rec/rec_r31_satrn/
  save_epoch_step: 1
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 10]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img: 
  # for data or label process
  character_dict_path: ppocr/utils/dict90.txt
  max_text_length: 30
  infer_mode: False
  use_space_char: False
  rm_symbol: True
  save_res_path: ./output/rec/predicts_satrn.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs: [3, 4]
    values: [0.001, 0.0001, 0.00001] 
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: SATRN
  Transform:
  Backbone:
    name: ShallowCNN
    in_channels: 3
    out_channels: 256
  Head:
    name: STARNHead

Loss:
  name: SARLoss

PostProcess:
  name: SARLabelDecode

Metric:
  name: RecMetric


Train:
  dataset:
    name: LMDBDataSet
    data_dir: I:/dataset/OCR/deep_text_recognition/data_lmdb/validation
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SARLabelEncode: # Class handling label
      - SATRNRecResizeImg:
          image_shape: [3, 32, 100] # h:48 w:[48,160]
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 2
    drop_last: True
    num_workers: 0
    use_shared_memory: False

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: I:/dataset/OCR/deep_text_recognition/data_lmdb/evaluation/CUTE80
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SARLabelEncode: # Class handling label
      - SATRNRecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'valid_ratio'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 0
    use_shared_memory: False
  
